# Generated by Django 5.1.2 on 2024-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='text',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='cards',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
