# Generated by Django 5.1.1 on 2024-11-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_flashcard_text_flashcard_cards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='streak',
            new_name='streak_count',
        ),
        migrations.AddField(
            model_name='student',
            name='last_activity_date',
            field=models.DateField(auto_now=True),
        ),
    ]
