# Generated by Django 5.1.2 on 2024-11-26 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_flashcard_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='base.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='chapter',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='base.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='base.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='base.student'),
            preserve_default=False,
        ),
    ]
