# Generated by Django 5.1.2 on 2024-11-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_chapter_subject_notes_chapter_quiz_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
    ]
