# Generated by Django 5.1.2 on 2024-11-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_chapter_subject_remove_flashcard_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='chapter',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='base.chapter'),
            preserve_default=False,
        ),
    ]
