# Generated by Django 5.1.2 on 2024-11-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_quiz_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='base.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='chapter',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='base.chapter'),
            preserve_default=False,
        ),
    ]
